name: with_git-secret

on: [ push , workflow_dispatch ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup for git-secret
      - run: |
          echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
          wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
          sudo apt-get update && sudo apt-get install git-secret
          # Create private key file
          echo $GPG_PRIVATE_KEY | tr ',' '\n' > ./private_key.gpg
          # Import private key
          gpg --import ./private_key.gpg
          
      - name: Decrypt secret files
      - run: |
          # Set environment variables for .gitsecret
          export SECRETS_DIR=with_git-secret/.gitsecret
          # Reveal secrets
          git secret reveal
          
      - name: Check decryption
        run: cat with_git-secret/message.txt
